---

- name: "create tinyci base dir"
  file:
    state: directory
    name: "/var/tinyci"

- name: "copy release to host"
  copy:
    src: release.tar.gz
    dest: /var/tinyci/release.tar.gz

- name: "Create the tinyCI binary directory"
  file:
    path: /var/tinyci/bin
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "Extract the binaries"
  unarchive:
    copy: false
    src: /var/tinyci/release.tar.gz
    dest: /var/tinyci/bin
    extra_opts:
      - "--strip-components=1"
      - "binaries/"
  register: release_binaries_updated

