---
- name: "make /etc/nginx dir"
  file:
    state: directory
    name: "/etc/nginx"
  when: tinyci.ui.tls.use_nginx_tls

- name: "upload certificate"
  copy:
    src: "nginx.pem"
    dest: "/etc/nginx/nginx.pem"
    mode: "0400"
  when: tinyci.ui.tls.use_nginx_tls

- name: "upload key"
  copy:
    src: "nginx.key"
    dest: "/etc/nginx/nginx.key"
    mode: "0400"
  when: tinyci.ui.tls.use_nginx_tls

- name: "upload dynamic certificate"
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/nginx.pem"
    mode: "0400"
  with_items:
    - "{{ tinyci.ui.tls.cert }}"
  when: not tinyci.ui.tls.use_nginx_tls

- name: "upload dynamic key"
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/nginx.key"
    mode: "0400"
  with_items:
    - "{{ tinyci.ui.tls.key }}"
  when: not tinyci.ui.tls.use_nginx_tls

- name: "create nginx configuration file"
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  register: nginx_config_file_state

- name: "start nginx"
  docker_container:
    pull: true
    name: "tinyci-nginx"
    image: "nginx"
    volumes:
      - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/nginx/nginx.pem:/etc/nginx/nginx.pem"
      - "/etc/nginx/nginx.key:/etc/nginx/nginx.key"
      - "{{ tinyci.ui.asset_dir }}:/usr/share/nginx/html"
    restart_policy: "on-failure"
    restart_retries: 2
    network_mode: host
    restart: "{{ nginx_config_file_state is changed }}"
