---

- name: "create nginx configuration file"
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx.conf"
  register: nginx_config_file_state

- name: "start nginx"
  docker_container:
    pull: true
    name: "tinyci-nginx"
    image: "nginx"
    volumes:
      - "/etc/nginx.conf:/etc/nginx/nginx.conf"
      - "{{ tinyci.ui.ca_dir }}:{{ tinyci.ui.ca_dir }}"
      - "{{ tinyci.ui.asset_dir }}:/usr/share/nginx/html"
    restart_policy: "on-failure"
    restart_retries: 2
    network_mode: host
    restart: "{{ nginx_config_file_state is changed }}"
