- hosts: all
  become: true
  roles:
    - system

- hosts: postgres
  become: true
  roles:
    - migration

- hosts: tinyci
  become: true
  roles:
    - release
    - tinyci-agents
    - ui

- hosts: runners
  become: true
  roles:
    - overlay-runner
