---

- name: "ensure /var/tinyci exists"
  file:
    name: "/var/tinyci"
    state: directory

- name: "untar UI into UI asset path"
  unarchive:
    copy: false
    src: "/var/tinyci/release.tar.gz"
    dest: "{{ tinyci.ui.asset_dir }}" 
    extra_opts:
    - --strip-components=2
    - "tinyci-{{ tinyci.version }}/ui"
