---

- name: "install dependencies"
  apt:
    name: "build-essential"

- name: Create the tinyCI runner config file
  template:
    src: runner-config.j2
    dest: "{{ tinyci.config.runner }}"
    owner: root
    group: root
    mode: '0600'
  register: overlay_runner_config_state

- name: Create the tinyCI binary directory
  file:
    path: /var/tinyci/bin
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create the systemd tinyCI runner unit
  template:
    src: overlay-runner.service.j2
    dest: /etc/systemd/system/overlay-runner.service
    owner: root
    group: root
    mode: '0755'

- name: Ensure overlay-runner is started
  systemd:
    name: overlay-runner
    enabled: true
    state: started
    daemon_reload: yes

- name: graceful restart of overlay-runner
  command: "pkill -HUP overlay-runner"
  when: overlay_runner_config_state is changed or release_binaries_updated is changed
