---

- name: "install dependencies"
  apt:
    name: "{{ item }}"
  with_items:
    - build-essential

- name: Create the tinyCI runner config file
  template:
    src: runner-config.j2
    dest: "{{ tinyci.config.runner }}"
    owner: root
    group: root
    mode: '0600'
  register: overlay_runner_config_state

- name: Create the systemd tinyCI runner unit
  template:
    src: overlay-runner.service.j2
    dest: /etc/systemd/system/overlay-runner.service
    owner: root
    group: root
    mode: '0755'

- name: Start overlay-runner
  systemd:
    name: overlay-runner
    state: restarted
    daemon_reload: yes
  when: overlay_runner_config_state is changed or release_binaries_updated is changed
